### PR TITLE
Update peerDependencies to support Grunt 1.0

### PR DESCRIPTION
**Pull request by gruntjs-updater**
Update peerDependencies to support Grunt 1.0

Hello,

This is an automated issue request to update the `peerDependencies` for your Grunt plugin.
We ask you to merge this and **publish a new release on npm** to get your plugin working in Grunt 1.0!

Read more here: http://gruntjs.com/blog/2016-02-11-grunt-1.0.0-rc1-released#peer-dependencies
Also on Twitter: https://twitter.com/gruntjs/status/700819604155707392

If you have any questions or you no longer have time to maintain this plugin, then please let us know in this thread.

Thanks for creating and working on this plugin!

(P.S. Close this PR if it is a mistake, sorry)

### CODE REVIEW

**Comment by DennisBecker** [comment]
Please update to grunt v.1.0.0 - I really like purifycss and would like to still use it in the future.

**Comment by XhmikosR** [comment]
@kennyt bump

**Comment by Mensae** [comment]
It's been a year now :( Can someone please merge/bump?

Really appreciate it.

Thanks

**Comment by XhmikosR** [comment]
@kennyt: you need to make a new patch release for this to have an effect.

**Comment by kennyt** [comment]
@XhmikosR done

**Comment by XhmikosR** [comment]
@kennyt: don't forget to push the git tag too.

**Pull request merged**
